/**
 * PreToolUse (Edit, Write, MultiEdit, NotebookEdit): blocks edits to files a tool generates or
 * that must never be hand-written, and tells Claude what to edit and run instead. The generated
 * list is `scripts/lib/generated-paths.ts`, the same one `.gitattributes` and CI follow.
 */
import { GENERATED_GLOBS } from '../../scripts/lib/generated-paths';
import { block, editedFile, readInput, run } from './hook.shared';

/** Paths that are not generated but still off limits, with the reason shown to Claude. */
const OFF_LIMITS: readonly { readonly glob: string; readonly why: string }[] = [
  {
    glob: '**/storage/vault/**',
    why: 'vault data is encrypted user data; use the synthetic fixtures in the vault tests',
  },
  { glob: '**/.turbo/**', why: 'a turbo cache folder' },
  { glob: 'release/**/*.zip', why: 'a packaged release; run `bun run package` instead' },
];

/** What to do instead, by generated path. The first matching pattern wins. */
const REGENERATE: readonly { readonly glob: string; readonly hint: string }[] = [
  {
    glob: 'bun.lock',
    hint: 'run `bun install` (add or remove packages with `bun add` or `bun remove`)',
  },
  { glob: 'Cargo.lock', hint: 'run a cargo command (`cargo update -p <crate>` or `cargo add`)' },
  {
    glob: '{packages/tokens,crates/design-tokens}/src/generated/**',
    hint: 'edit the token sources in packages/tokens/src (tokens/ or themes/), then run `bun run tokens`',
  },
  {
    glob: 'packages/design-system/src/icons/*.generated.ts',
    hint: 'run `bun x --no-install turbo run generate --filter=@genslate/design-system`',
  },
  {
    glob: 'programs/desktop/*/src-tauri/{gen,permissions/autogenerated}/**',
    hint: 'tauri-build regenerates it on `cargo build`; change src-tauri/capabilities or tauri.conf.json instead',
  },
];

/** Case-insensitive, like the Windows file system the owner works on (`Cargo.LOCK` is `Cargo.lock`). */
const matches = (glob: string, path: string): boolean =>
  new Bun.Glob(glob.toLowerCase()).match(path.toLowerCase());

/** Why `relPath` (relative to the repository root, `/` separators) must not be edited, if so. */
export function protectedReason(relPath: string): string | undefined {
  const generated = GENERATED_GLOBS.find((glob) => matches(glob, relPath));
  if (generated !== undefined) {
    const hint = REGENERATE.find((entry) => matches(entry.glob, relPath))?.hint;
    return hint === undefined
      ? 'generated; edit its source and regenerate it'
      : `generated; ${hint}`;
  }
  return OFF_LIMITS.find((entry) => matches(entry.glob, relPath))?.why;
}

if (import.meta.main) {
  await run(async () => {
    const file = editedFile(await readInput());
    if (file === undefined) return;
    const reason = protectedReason(file);
    if (reason !== undefined) block(`Blocked: ${file} is ${reason}.`);
  });
}
