/**
 * Canonical token key sets. Adding a key here forces every theme to define it
 * (see `ThemeDefinition` in token.types.ts) and every emitter to output it.
 */

export const NORD_COLOR_KEYS = [
  'nord-0',
  'nord-1',
  'nord-2',
  'nord-3',
  'nord-4',
  'nord-5',
  'nord-6',
  'nord-7',
  'nord-8',
  'nord-9',
  'nord-10',
  'nord-11',
  'nord-12',
  'nord-13',
  'nord-14',
  'nord-15',
] as const;

/**
 * Derived shades. Naming: `nord-{n}-{l|d}{ΔL×100}` = OKLCH lightness shift,
 * `nord-{a}-m{b}-{pct}` = pct% of a mixed over b, plus named specials.
 */
export const DERIVED_COLOR_KEYS = [
  'nord-0-d03',
  'nord-3-bright',
  'nord-3-bright-d05',
  'nord-4-m0-85',
  'nord-4-m0-75',
  'nord-4-m0-35',
  'nord-3-m6-45',
  'snow-bright',
  'nord-8-l03',
  'nord-8-d04',
  'nord-9-l04',
  'nord-9-l08',
  'nord-9-d14',
  'nord-9-d20',
  'nord-10-d08',
  'nord-10-d10',
  'nord-10-d12',
  'nord-11-l16',
  'nord-11-d08',
  'nord-11-d10',
  'nord-13-l03',
  'nord-13-d08',
  'nord-13-d20',
  'nord-13-d36',
  'nord-14-l03',
  'nord-14-d08',
  'nord-14-d12',
  'nord-14-d28',
  'nord-7-d24',
  'nord-8-d30',
  'nord-13-d28',
  'nord-14-d20',
  'nord-15-d12',
  'nord-15-d20',
  'nord-12-d12',
] as const;

/** T1 semantic colour roles → `--gs-color-{key}` → Tailwind `bg-{key}`, `text-{key}`, … */
export const SEMANTIC_COLOR_KEYS = [
  // Surfaces
  'canvas',
  'surface',
  'surface-sidebar',
  'surface-panel',
  'surface-raised',
  'surface-popover',
  'surface-dialog',
  'surface-sunken',
  'field',
  'scrim',
  // Over photos and video (the same in every theme)
  'media-shade',
  'on-media',
  // Borders
  'border-subtle',
  'border',
  'border-strong',
  // Text
  'fg-strong',
  'fg',
  'fg-secondary',
  'fg-muted',
  'fg-disabled',
  'on-accent',
  // Accent
  'accent',
  'accent-hover',
  'accent-active',
  'accent-fg',
  'accent-subtle',
  'accent-border',
  // Focus & selection
  'focus',
  'focus-halo',
  'selection',
  'selection-inactive',
  // Fills & controls
  'fill-hover',
  'fill-pressed',
  'fill-selected-inactive',
  'control',
  'control-hover',
  'control-pressed',
  'track',
  'thumb',
  // Status: solid · solid hover · text on solid · text on surfaces · subtle bg · border
  'danger',
  'danger-hover',
  'on-danger',
  'danger-fg',
  'danger-subtle',
  'danger-border',
  'warning',
  'warning-hover',
  'on-warning',
  'warning-fg',
  'warning-subtle',
  'warning-border',
  'success',
  'success-hover',
  'on-success',
  'success-fg',
  'success-subtle',
  'success-border',
  'info',
  'info-hover',
  'on-info',
  'info-fg',
  'info-subtle',
  'info-border',
] as const;

/** T2 window-chrome roles → `--gs-{key}` → Tailwind `bg-{key}`, `text-{key}`, … */
export const CHROME_COLOR_KEYS = [
  'titlebar-bg',
  'titlebar-bg-inactive',
  'titlebar-fg',
  'titlebar-fg-inactive',
  'titlebar-border',
  'command-center-bg',
  'command-center-bg-hover',
  'command-center-border',
  'statusbar-bg',
  'statusbar-fg',
  'statusbar-bg-hover',
  'statusbar-bg-active',
  'statusbar-accent-bg',
  'statusbar-accent-fg',
  'statusbar-accent-bg-hover',
  'statusbar-border',
  'tab-strip-bg',
  'tab-active-bg',
  'tab-indicator',
  'tooltip-bg',
  'tooltip-fg',
  'tooltip-border',
  'traffic-close',
  'traffic-minimize',
  'traffic-maximize',
  'traffic-close-pressed',
  'traffic-minimize-pressed',
  'traffic-maximize-pressed',
  'traffic-inactive',
  'traffic-rim',
  'traffic-glyph',
  'scrollbar-thumb',
  'scrollbar-thumb-hover',
  'scrollbar-thumb-active',
  // Terminal: surface, text, cursor and the 16 ANSI colours (xterm.js theme)
  'terminal-bg',
  'terminal-fg',
  'terminal-cursor',
  'terminal-cursor-text',
  'terminal-selection',
  'terminal-black',
  'terminal-red',
  'terminal-green',
  'terminal-yellow',
  'terminal-blue',
  'terminal-magenta',
  'terminal-cyan',
  'terminal-white',
  'terminal-bright-black',
  'terminal-bright-red',
  'terminal-bright-green',
  'terminal-bright-yellow',
  'terminal-bright-blue',
  'terminal-bright-magenta',
  'terminal-bright-cyan',
  'terminal-bright-white',
  // Profile and tab accents (a shell's colour in tabs, menus and the sessions list)
  'profile-frost',
  'profile-red',
  'profile-orange',
  'profile-yellow',
  'profile-green',
  'profile-purple',
] as const;

/** Flat style: surfaces are separated by borders and tone, so the only shadow is the floating popup's. */
export const SHADOW_KEYS = ['popover'] as const;

/**
 * Themed cursors → `--gs-cursor-{key}` → Tailwind `cursor-{key}`. Every key but `interactive` is
 * a CSS cursor keyword (and its fallback); `interactive` is the Frost arrow for controls.
 */
export const CURSOR_KEYS = [
  'default',
  'interactive',
  'pointer',
  'text',
  'vertical-text',
  'not-allowed',
  'no-drop',
  'progress',
  'wait',
  'help',
  'copy',
  'alias',
  'context-menu',
  'grab',
  'grabbing',
  'move',
  'all-scroll',
  'crosshair',
  'col-resize',
  'row-resize',
  'ew-resize',
  'ns-resize',
  'nwse-resize',
  'nesw-resize',
  'zoom-in',
  'zoom-out',
] as const;

/** The colours a theme paints its cursors with. */
export const CURSOR_PAINT_KEYS = [
  'glyph',
  'rim',
  'accent',
  'on-accent',
  'danger',
  'success',
  'info',
] as const;
