/** Helpers shared by every token emitter. */

import type { Easing } from '../../src/token.types';

export const GENERATED_BANNER =
  'GENERATED by packages/tokens/scripts/build-tokens.ts — do not edit. Run `bun run tokens`.';

export const cssBanner = () => `/* ${GENERATED_BANNER} */\n`;
export const tsBanner = () => `// ${GENERATED_BANNER}\n`;
export const rustBanner = () => `// ${GENERATED_BANNER}\n`;

export const px = (n: number) => (n === 0 ? '0' : `${n}px`);

/** Formats a CSS declaration block. */
export function block(
  selector: string,
  declarations: ReadonlyArray<readonly [string, string]>,
  indent = '',
): string {
  const body = declarations.map(([k, v]) => `${indent}  ${k}: ${v};`).join('\n');
  return `${indent}${selector} {\n${body}\n${indent}}\n`;
}

export function easingToCss(easing: Easing): string {
  return `cubic-bezier(${easing.points.join(', ')})`;
}

/** `surface-sidebar` → `SURFACE_SIDEBAR` / `surface_sidebar`. */
export const screamingSnake = (key: string) => key.replace(/[-.]/g, '_').toUpperCase();
export const snake = (key: string) => key.replace(/[-.]/g, '_').toLowerCase();

export function entries<K extends string, V>(record: Readonly<Record<K, V>>): Array<[K, V]> {
  return Object.entries(record) as Array<[K, V]>;
}
