import { describe, expect, test } from 'bun:test';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..', '..');

/** research/port-map.md §2: skeleton paths that are typos or SlateSuite names and must not exist. */
const MISSPELLED_PATHS: readonly string[] = [
  'crates/paths/src/enviroment.rs',
  'crates/paths/src/resolver.rs',
  'crates/design-tokens/src/generated/theme-colors.rs',
  'crates/core',
  'programs/desktop/launcher/src-tauri/premissions',
  'programs/desktop/launcher/src-tauri/tauri.config.json',
  'programs/desktop/launcher/src/launcher/launcher.context.tsx',
  'programs/desktop/launcher/src/launcher/launcher.provider.tsx',
  'programs/desktop/launcher/installDir/storage/users/shared/Recycle Bin',
  'programs/desktop/launcher/other/launcher/config',
  'programs/desktop/launcher/other/launcher/databases',
  'packages/design-system/src/utlis',
  'packages/design-system/src/fonts',
  'packages/tokens/scripts/emit/emit.sharedts',
  '.claude/memory/lession-learned.md',
  '.cursor/extesions.json',
  '.github/codeql/coeql-config.yml',
];

/** Generated or runtime folders: they may exist on disk after a build, but are never committed. */
const NEVER_TRACKED: readonly string[] = [
  'programs/desktop/launcher/src-tauri/gen/',
  'programs/desktop/launcher/src-tauri/permissions/autogenerated/',
  '.cursor/hooks/state/',
  'node_modules/',
  'Recycle Bin/',
];

function git(args: readonly string[]): { code: number; out: string } {
  const result = Bun.spawnSync(['git', ...args], { cwd: ROOT, stdout: 'pipe', stderr: 'pipe' });
  return { code: result.exitCode, out: result.stdout.toString() };
}

function isIgnored(path: string): boolean {
  return git(['check-ignore', '-q', '--no-index', path]).code === 0;
}

async function readJson(path: string): Promise<Record<string, unknown>> {
  return (await Bun.file(join(ROOT, path)).json()) as Record<string, unknown>;
}

describe('repository layout', () => {
  test('no_known_typos_remain', () => {
    const present = MISSPELLED_PATHS.filter((path) => existsSync(join(ROOT, path)));
    expect(present).toEqual([]);

    const tracked = git(['ls-files']).out.split('\n');
    const committed = NEVER_TRACKED.filter((needle) =>
      tracked.some(
        (file) => file === needle || file.startsWith(needle) || file.includes(`/${needle}`),
      ),
    );
    expect(committed).toEqual([]);
  });

  test('root_package_is_slatecore_authored_by_genslate', async () => {
    const pkg = await readJson('package.json');
    expect(pkg['name']).toBe('slatecore');
    expect(pkg['author']).toBe('GENSLATE');
    expect(pkg['private']).toBe(true);

    const cargo = Bun.TOML.parse(await Bun.file(join(ROOT, 'Cargo.toml')).text()) as {
      workspace?: { package?: { authors?: unknown } };
    };
    expect(cargo.workspace?.package?.authors).toEqual(['GENSLATE']);
  });

  test('required_paths_exist', () => {
    const required = [
      'turbo.json',
      'Cargo.toml',
      'crates/vault/Cargo.toml',
      'packages/config-typescript/package.json',
      'programs/webapp/example/package.json',
      'programs/desktop/launcher/src-tauri/tauri.conf.json',
    ];
    const missing = required.filter((path) => !existsSync(join(ROOT, path)));
    expect(missing).toEqual([]);
  });

  test('gitignore_covers_build_output', () => {
    const mustIgnore = [
      'target/debug/slatecore-launcher.exe',
      // Not a real package: git refuses paths beyond the isolated linker's symlinks.
      'node_modules/left-pad/index.js',
      'packages/tokens/node_modules/left-pad/index.js',
      'programs/webapp/example/dist/index.html',
      '.turbo/cache/abc.tar.zst',
      'packages/tokens/.turbo/turbo-test.log',
      'programs/desktop/launcher/src-tauri/gen/schemas/desktop-schema.json',
      'programs/desktop/launcher/src-tauri/permissions/autogenerated/commands.toml',
      'release/slatecore-launcher-0.1.0-base.zip',
      'release/.archive/slatecore-launcher-0.0.9-base.zip',
      'programs/desktop/launcher/installDir/programs/genslate/launcher/slatecore-launcher.exe',
      'programs/desktop/launcher/installDir/programs/portableapps.com/App/app.exe',
      'programs/desktop/launcher/installDir/storage/users/shared/Documents/note.txt',
      'programs/desktop/launcher/installDir/storage/vault/files/0123.gvf',
      'programs/desktop/launcher/other/launcher/cache/webview2/Local State',
      'programs/desktop/launcher/other/launcher/logs/launcher.log',
      'programs/desktop/launcher/other/launcher/database/recent.toml',
      '.env',
      '.env.local',
      '.claude/settings.local.json',
      '.cursor/hooks/state/continual-learning.json',
      'tsconfig.tsbuildinfo',
    ];
    const mustKeep = [
      '.env.example',
      'release/.gitkeep',
      'release/.archive/.gitkeep',
      'programs/desktop/launcher/installDir/programs/genslate/launcher/.gitkeep',
      'programs/desktop/launcher/installDir/storage/vault/.gitkeep',
      'programs/desktop/launcher/other/launcher/cache/.gitkeep',
      'programs/desktop/launcher/other/launcher/configs/settings.toml',
      '.claude/settings.json',
    ];
    expect(mustIgnore.filter((path) => !isIgnored(path))).toEqual([]);
    expect(mustKeep.filter((path) => isIgnored(path))).toEqual([]);
  });
});
