#!/usr/bin/env bun
/**
 * Generates the typed Codicon name list from @vscode/codicons so `<Icon name="codicon:…" />`
 * is checked at compile time.
 *
 *   bun scripts/build-icons.ts           write src/icons/codicon-names.generated.ts
 *   bun scripts/build-icons.ts --check   fail when the committed file is stale
 */

import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { join, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const csvPath = require.resolve('@vscode/codicons/dist/codicon.csv');
const outPath = resolve(import.meta.dir, '../src/icons/codicon-names.generated.ts');

const csv = await readFile(csvPath, 'utf8');
const names = [
  ...new Set(
    csv
      .split('\n')
      .slice(1)
      .map((line) => line.split(',')[0]?.trim())
      .filter((name): name is string => Boolean(name)),
  ),
].sort();

const content = `// GENERATED by packages/design-system/scripts/build-icons.ts from @vscode/codicons — do not edit.

/** Every Codicon glyph name (${names.length}). */
export const CODICON_NAMES = [
${names.map((n) => `  '${n}',`).join('\n')}
] as const;

export type CodiconName = (typeof CODICON_NAMES)[number];
`;

const current = await readFile(outPath, 'utf8').catch(() => null);
if (process.argv.includes('--check')) {
  if (current !== content) {
    console.error(
      `✗ ${join('src/icons', 'codicon-names.generated.ts')} is stale — run \`bun scripts/build-icons.ts\``,
    );
    process.exit(1);
  }
  console.log('✓ codicon names up to date');
} else if (current !== content) {
  await writeFile(outPath, content);
  console.log(`✓ wrote ${names.length} codicon names`);
}
