/**
 * Files that tools write and people never edit: lockfiles, token outputs, icon sets and Tauri's
 * generated schemas. Hooks and drift checks read this list (globs relative to the repo root,
 * `/` separators), so a new generated folder is added here once.
 */
export const GENERATED_GLOBS: readonly string[] = [
  'bun.lock',
  'Cargo.lock',
  'packages/tokens/src/generated/**',
  'crates/design-tokens/src/generated/**',
  'packages/design-system/src/icons/*.generated.ts',
  'programs/desktop/*/src-tauri/gen/**',
  'programs/desktop/*/src-tauri/permissions/autogenerated/**',
  '**/*.generated.ts',
];
